### ISSUE TITLE
[doc] Installation Guide is not up to date as is links to lp instead to github

### ISSUE THREAD

**Issue by OSguard** [OCA/connector-magento#64]
https://github.com/OCA/connector-magento/blob/7.0/magentoerpconnect/doc/guides/installation_guide.rst

**Comment by OSguard** [comment]
fixed with #66

**Comment by guewen** [comment]
Still a problem to actually update the pages on http://odoo-magento-connector.com/guides/installation_guide.html
I pushed the changes on the GitHub pages project and it failed the build due to CNAME issues (there are 2 forks with the same CNAME), I think I have to contact the GitHub support.

**Comment by OSguard** [comment]
ah, i don't know how the webside is deployed. So it is made from github?
i reopen the issue until wesite is up to date.

**Comment by guewen** [comment]
I could finally resolve the CNAME issue.

@OSguard Yes, I push the builds of the docs on GitHub pages.
